name: Publish production image to GHCR (camap-hx)

on:
  push:
    branches: [ "master" ]
    # Capture tous les v* puis on filtre strictement plus bas
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  verify-prod:
    name: Verify tag is vX.Y.Z from master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Validate tag format vX.Y.Z (no pre-release)
        id: tag
        shell: bash
        run: |
          ref="${GITHUB_REF##*/}"   # ex: v2.0.8
          echo "ref_name=$ref" >> $GITHUB_OUTPUT
          if [[ ! "$ref" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Tag non conforme (attendu: vX.Y.Z), reçu: $ref"
            exit 1
          fi
          echo "✅ Tag conforme: $ref"

      - name: Ensure tag commit is contained in origin/master
        shell: bash
        run: |
          git fetch origin +refs/heads/master:refs/remotes/origin/master
          if ! git branch --remotes --contains HEAD | grep -q 'origin/master'; then
            echo "❌ Ce tag n'est pas créé depuis la branche master."
            exit 1
          fi
          echo "✅ Tag créé depuis un commit présent dans origin/master"

  build-and-push:
    name: Build & push camap-hx (prod)
    needs: verify-prod
    # Ceinture-bretelles : n’exécuter que pour un tag vX.Y.Z (sans '-...')
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-')
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/camap-app/camap-hx
    steps:
      - uses: actions/checkout@v4

      - name: Extract versions
        id: ver
        shell: bash
        run: |
          tag="${GITHUB_REF##*/}"          # v2.0.8
          semver="${tag#v}"                # 2.0.8
          major="${semver%%.*}"            # 2
          minor_patch="${semver#${major}.}"   # 0.8
          minor="${minor_patch%%.*}"       # 0
          major_minor="${major}.${minor}"  # 2.0
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "semver=$semver" >> $GITHUB_OUTPUT
          echo "major=$major" >> $GITHUB_OUTPUT
          echo "major_minor=$major_minor" >> $GITHUB_OUTPUT
          echo "▶ tag=$tag semver=$semver major=$major major_minor=$major_minor"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push (prod)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./camap-hx.Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.ver.outputs.tag }}
            ${{ env.IMAGE_NAME }}:${{ steps.ver.outputs.major_minor }}
            ${{ env.IMAGE_NAME }}:${{ steps.ver.outputs.major }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
