name: Publish staging image to GHCR

on:
  push:
    tags:
      - 'staging-v*'
      - 'staging-*'

permissions:
  contents: read
  packages: write

jobs:
  verify-staging:
    name: Verify tag points to staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Ensure HEAD is contained in origin/staging
        run: |
          git fetch origin +refs/heads/staging:refs/remotes/origin/staging
          if ! git branch --remotes --contains HEAD | grep -q 'origin/staging'; then
            echo "❌ Ce tag n'est pas créé depuis la branche staging." >&2
            exit 1
          fi

  build-and-push:
    name: Build & push camap-hx
    needs: verify-staging
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/<OWNER>/camap-hx
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        id: ver
        run: |
          ref="${GITHUB_REF##*/}"    # ex: staging-v1.2.3
          echo "tag=$ref" >> $GITHUB_OUTPUT
          echo "short=${ref#staging-}" >> $GITHUB_OUTPUT  # ex: v1.2.3 ou 2025.10.25.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          # Si ton Dockerfile n'est pas à la racine, précise: file: ./camap-hx.Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.ver.outputs.tag }}       # ex: staging-v1.2.3
            ${{ env.IMAGE_NAME }}:${{ steps.ver.outputs.short }}     # ex: v1.2.3
            ${{ env.IMAGE_NAME }}:staging                             # dernier build staging
          cache-from: type=gha
          cache-to: type=gha,mode=max
